import tw from '../../styles/tailwind';

export const knowledgeStyles = {
  safeArea: tw`flex-1 bg-pearl`,
  container: tw`p-4 pb-12`,
  header: tw`mb-3`,
  title: tw`text-xl font-extrabold text-pine tracking-tight`,
  subtitle: tw`text-xs text-slate mt-0.5`,
  categoryRow: tw`flex-row mb-3.5`,
  categoryChip: tw`px-3.5 py-1.5 rounded-full bg-gray-200 mr-2`,
  categoryChipActive: tw`bg-brand-forest shadow`,
  categoryText: tw`text-xs font-bold text-slate`,
  categoryTextActive: tw`text-white`,
  articleCard: tw`my-1.5 p-4 bg-white rounded-2xl border border-gray-100 shadow-sm`,
  cardTop: tw`flex-row justify-between items-center mb-1.5`,
  badge: tw`bg-brand-sage-light px-2 py-0.5 rounded-md`,
  badgeText: tw`text-brand-forest text-[11px] font-bold`,
  readTime: tw`text-[11px] text-gray-500 font-medium`,
  articleTitle: tw`text-sm font-extrabold text-pine mb-1`,
  articleSummary: tw`text-xs text-slate leading-4.5 mb-2`,
  readMore: tw`text-xs font-bold text-brand-emerald`,
  modalOverlay: tw`flex-1 bg-black/50 justify-end`,
  modalContent: tw`bg-white rounded-t-3xl p-5 max-h-[80%]`,
  modalHeader: tw`flex-row justify-between items-center mb-3`,
  closeBtn: tw`text-xs font-bold text-slate py-1 px-2.5 rounded-lg bg-gray-100`,
  modalBody: tw`my-2`,
  modalTitle: tw`text-lg font-extrabold text-pine mb-1.5`,
  modalReadTime: tw`text-xs text-gray-500 mb-3.5`,
  modalText: tw`text-xs text-pine leading-5 mb-5`,
};
