import { StyleSheet, Dimensions } from 'react-native';
import { FONTS } from '../../constants/typography';
import { COLORS } from '../../constants/colors';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const notificationModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(11, 23, 16, 0.45)', // Soft dark pine blur overlay
    justifyContent: 'flex-end',
  },
  modalBackdropTouch: {
    ...StyleSheet.absoluteFillObject,
  },
  glassModalContent: {
    height: SCREEN_HEIGHT * 0.78,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: 36,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.90)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    overflow: 'hidden',
  },
  modalDragHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(27, 67, 44, 0.20)',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  modalTitle: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 20,
    color: '#0F2418',
    letterSpacing: -0.4,
  },
  modalSubtitle: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 12,
    color: '#4A6354',
    marginTop: 1,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.10)',
  },
  closeBtnText: {
    fontFamily: FONTS.roundedExtraBold,
    fontSize: 14,
    color: '#1B432C',
  },

  // Glassy Segmented Tab Bar
  tabBarWrap: {
    flexDirection: 'row',
    backgroundColor: 'rgba(232, 243, 236, 0.70)',
    borderRadius: 16,
    padding: 4,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.80)',
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBtnActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  tabBtnText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12.5,
    color: '#4A6354',
  },
  tabBtnTextActive: {
    fontFamily: FONTS.roundedBlack,
    color: '#1B432C',
  },

  modalScrollBody: {
    flex: 1,
  },

  // Glassy White Gradient Card Item
  glassNotificationCard: {
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.95)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  cardUnreadMarker: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#10B981',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  cardCategoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 8,
  },
  cardCategoryText: {
    fontFamily: FONTS.roundedExtraBold,
    fontSize: 10,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  cardTimeText: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 11,
    color: '#849C8D',
  },
  cardTitle: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 14.5,
    color: '#0F2418',
    marginBottom: 4,
    lineHeight: 19,
  },
  cardMessage: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 12.5,
    color: '#4A6354',
    lineHeight: 18,
  },
  cardActionRow: {
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  cardActionBtn: {
    backgroundColor: 'rgba(27, 67, 44, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.12)',
  },
  cardActionBtnText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 11.5,
    color: '#1B432C',
  },

  // Reminder Settings Item Row
  settingsGlassCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.90)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  settingIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#E8F3EC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  settingTextWrap: {
    flex: 1,
    marginRight: 10,
  },
  settingTitle: {
    fontFamily: FONTS.roundedBold,
    fontSize: 14,
    color: '#0F2418',
  },
  settingSub: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 11.5,
    color: '#4A6354',
    marginTop: 2,
  },

  // Bottom Action Button
  modalFooterBtn: {
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 4,
  },
  modalFooterBtnText: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 15,
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
});
