import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';
import { FONTS } from '../../constants/typography';

export const mealLogStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background, // Clean Pearl Sage #F7FAF8
  },
  container: {
    padding: 16,
    paddingTop: 8,
    paddingBottom: 48,
  },
  header: {
    marginBottom: 12,
  },
  title: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 22,
    color: '#0F2418',
    letterSpacing: -0.5,
    lineHeight: 27,
  },
  subtitle: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 12.5,
    color: '#4A6354',
    marginTop: 2,
    letterSpacing: -0.1,
  },
  galleryLabel: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 10.5,
    color: '#849C8D',
    letterSpacing: 1.2,
    marginBottom: 8,
    textTransform: 'uppercase',
    marginLeft: 2,
  },
  galleryScroll: {
    marginBottom: 14,
    marginLeft: -4,
  },
  galleryContent: {
    gap: 8,
    paddingLeft: 4,
    paddingRight: 16,
  },
  galleryCard: {
    width: 96,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 6,
    borderWidth: 1.5,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    alignItems: 'center',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  galleryCardActive: {
    borderColor: '#10B981',
    backgroundColor: '#F0FDF4',
  },
  galleryCardThumb: {
    width: 84,
    height: 64,
    borderRadius: 10,
    marginBottom: 4,
  },
  galleryCardTitle: {
    fontFamily: FONTS.roundedBold,
    fontSize: 10.5,
    color: '#0F2418',
    width: '100%',
    textAlign: 'center',
  },
  galleryCardTag: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 8.5,
    color: '#2D6A4F',
    backgroundColor: '#E8F3EC',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    marginTop: 2,
    overflow: 'hidden',
  },
  photoContainer: {
    marginBottom: 14,
    width: '100%',
  },
  photoCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#2D6A4F',
    backgroundColor: '#E8F3EC',
    borderRadius: 20,
    minHeight: 168,
  },
  photoAttachedCard: {
    width: '100%',
    height: 168,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#1B432C',
    position: 'relative',
  },
  attachedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 36, 24, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  scanScannerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scanLine: {
    height: 3,
    backgroundColor: '#10B981',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 4,
    width: '100%',
  },
  scanStatusText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12.5,
    color: '#FFFFFF',
    marginTop: 10,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  detectedIngredientsCard: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    borderRadius: 20,
    padding: 12,
    marginBottom: 14,
  },
  detectedLabel: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 10,
    color: '#047857',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  detectedChip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3.5,
  },
  detectedChipText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 11,
    color: '#065F46',
  },
  fieldHeading: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 11,
    color: '#849C8D',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginLeft: 2,
  },
  photoText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 13.5,
    color: '#1B432C',
    marginTop: 8,
  },
  photoSub: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 11,
    color: '#6B8775',
    marginTop: 3,
    textAlign: 'center',
  },
  catScroll: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  catChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    marginRight: 8,
  },
  catChipActive: {
    backgroundColor: '#1B432C',
    borderColor: '#1B432C',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  catText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12,
    color: '#4A6354',
  },
  catTextActive: {
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    marginBottom: 14,
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 11,
    color: '#849C8D',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  fieldLabel: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12,
    color: '#0F2418',
    marginBottom: 4,
  },
  textInput: {
    fontFamily: FONTS.roundedSemiBold,
    backgroundColor: '#F7FAF8',
    borderWidth: 1,
    borderColor: '#D1DDD6',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13.5,
    color: '#0F2418',
    marginBottom: 10,
  },
  
  // Dedicated Separate Sugar & Sodium Cards
  nutrientCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  nutrientCardTitle: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12.5,
    color: '#0F2418',
  },
  nutrientCardContext: {
    fontFamily: FONTS.roundedBold,
    fontSize: 11,
    color: '#849C8D',
  },
  nutrientInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderWidth: 1,
    borderColor: '#D1DDD6',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginVertical: 6,
  },
  nutrientInput: {
    flex: 1,
    fontFamily: FONTS.displayExtraBold,
    fontSize: 17,
    color: '#0F2418',
    paddingVertical: 6,
  },
  nutrientUnit: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12,
    color: '#4A6354',
    marginLeft: 6,
  },
  highSodiumInputWrap: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  nutrientHelperText: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 11,
    color: '#4A6354',
    marginTop: 2,
    lineHeight: 15,
  },

  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  gridCol: {
    flex: 1,
  },
  warningBox: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FCD34D',
    padding: 10,
    borderRadius: 14,
    marginVertical: 8,
  },
  warningText: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 12,
    color: '#92400E',
    lineHeight: 16,
  },
  submitBtn: {
    backgroundColor: '#1B432C',
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  submitBtnText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 14.5,
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  // Visual History Gallery Grid (3 Columns)
  gridContainer: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
    marginTop: 10,
  },
  gridItem: {
    width: '31.3%' as const,
    aspectRatio: 1,
    borderRadius: 16,
    overflow: 'hidden' as const,
    position: 'relative' as const,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    marginBottom: 2,
  },
  gridImage: {
    width: '100%' as const,
    height: '100%' as const,
  },
  gridWarningDot: {
    position: 'absolute' as const,
    top: 6,
    right: 6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
    zIndex: 5,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  gridItemOverlay: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 36,
    paddingHorizontal: 4,
    paddingBottom: 4,
    justifyContent: 'flex-end' as const,
    alignItems: 'center' as const,
  },
  gridCategoryText: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 9,
    color: '#A7F3D0',
    letterSpacing: 0.3,
    textTransform: 'uppercase' as const,
  },
  plusCard: {
    width: '31.3%' as const,
    aspectRatio: 1,
    borderRadius: 16,
    borderStyle: 'dashed' as const,
    borderWidth: 1.5,
    borderColor: '#D1DDD6',
    backgroundColor: '#E8F3EC',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 1,
    marginBottom: 2,
  },
  plusIcon: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 20,
    color: '#2D6A4F',
    lineHeight: 22,
  },
  plusText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 10.5,
    color: '#2D6A4F',
  },
  loggerHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 14,
    marginTop: 4,
  },
  backBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#E8F3EC',
    borderWidth: 1,
    borderColor: '#D1DDD6',
  },
  backBtnText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 11.5,
    color: '#2D6A4F',
  },
  loggerHeadingText: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 10.5,
    color: '#849C8D',
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
  },

  // Meal Detail Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 36, 24, 0.45)',
    justifyContent: 'center' as const,
  },
  detailModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 20,
    width: '90%' as const,
    maxWidth: 360,
    alignSelf: 'center' as const,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  detailModalHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 6,
  },
  detailModalCategory: {
    fontFamily: FONTS.roundedBold,
    fontSize: 9.5,
    color: '#1B432C',
    backgroundColor: '#E8F3EC',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    letterSpacing: 0.2,
  },
  detailModalTime: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 10.5,
    color: '#849C8D',
  },
  detailModalTitle: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 17,
    color: '#0F2418',
    letterSpacing: -0.3,
    marginBottom: 2,
  },
  detailModalPortion: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12,
    color: '#6B8775',
    marginBottom: 12,
  },
  detailModalPhotoWrap: {
    width: '100%' as const,
    height: 140,
    borderRadius: 16,
    overflow: 'hidden' as const,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  detailModalPhoto: {
    width: '100%' as const,
    height: '100%' as const,
  },
  detailModalMacros: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    backgroundColor: '#F7FAF8',
    borderRadius: 16,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.04)',
  },
  detailModalMacroBox: {
    alignItems: 'center' as const,
    flex: 1,
  },
  detailModalMacroVal: {
    fontFamily: FONTS.displayExtraBold,
    fontSize: 13.5,
    color: '#0F2418',
  },
  detailModalMacroLabel: {
    fontFamily: FONTS.roundedBold,
    fontSize: 9,
    color: '#849C8D',
    marginTop: 1,
  },
  detailMascotFeedback: {
    backgroundColor: '#F0FDF4',
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    borderLeftWidth: 3,
    borderLeftColor: '#10B981',
  },
  detailMascotText: {
    fontFamily: FONTS.roundedSemiBold,
    fontSize: 11,
    color: '#065F46',
    lineHeight: 15.5,
  },
  detailModalCloseBtn: {
    backgroundColor: '#1B432C',
    borderRadius: 16,
    paddingVertical: 11,
    alignItems: 'center' as const,
  },
  detailModalCloseBtnText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 13,
    color: '#FFFFFF',
    letterSpacing: 0.1,
  },

  // Mock Camera Viewfinder Styles
  cameraScreenBg: {
    flex: 1,
    backgroundColor: '#000000',
  },
  cameraHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 14,
    backgroundColor: '#0F172A',
    borderBottomWidth: 1,
    borderColor: '#1E293B',
  },
  cameraCancelBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#334155',
  },
  cameraCancelBtnText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12,
    color: '#E2E8F0',
  },
  cameraTitle: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 14,
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  cameraViewport: {
    flex: 1,
    backgroundColor: '#000000',
    position: 'relative' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  viewportImage: {
    width: '100%' as const,
    height: '100%' as const,
    resizeMode: 'cover' as const,
  },
  viewportOverlay: {
    position: 'absolute' as const,
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  viewportOverlayTitle: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 9.5,
    color: '#10B981',
    letterSpacing: 1.5,
  },
  viewportOverlaySub: {
    fontFamily: FONTS.roundedBold,
    fontSize: 12.5,
    color: '#F8FAFC',
    marginTop: 2,
  },
  cameraControlPanel: {
    backgroundColor: '#0F172A',
    paddingVertical: 20,
    borderTopWidth: 1,
    borderColor: '#1E293B',
  },
  presetHeading: {
    fontFamily: FONTS.roundedBlack,
    fontSize: 9.5,
    color: '#64748B',
    letterSpacing: 1,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  cameraPresetsScroll: {
    maxHeight: 52,
    marginBottom: 16,
  },
  cameraPresetsContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  cameraPresetChip: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#1E293B',
    borderWidth: 1.5,
    borderColor: '#334155',
  },
  cameraPresetChipActive: {
    borderColor: '#10B981',
    backgroundColor: '#064E3B',
  },
  cameraPresetThumb: {
    width: 26,
    height: 26,
    borderRadius: 5,
  },
  cameraPresetLabel: {
    fontFamily: FONTS.roundedBold,
    fontSize: 11,
    color: '#94A3B8',
  },
  cameraPresetLabelActive: {
    color: '#FFFFFF',
  },
  shutterContainer: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  shutterBtn: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  shutterInnerRing: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#10B981',
  },

  // Mock Scan Screen
  scanningScreenBg: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scanPhotoWrap: {
    width: '100%' as const,
    height: '100%' as const,
    position: 'relative' as const,
  },
  scanningImage: {
    width: '100%' as const,
    height: '100%' as const,
    resizeMode: 'cover' as const,
  },

  // Log Name Entry Form View Photo
  formPhotoCard: {
    width: '100%' as const,
    height: 160,
    borderRadius: 20,
    overflow: 'hidden' as const,
    position: 'relative' as const,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
  },
  formPhotoImage: {
    width: '100%' as const,
    height: '100%' as const,
    resizeMode: 'cover' as const,
  },
  scannedBadge: {
    position: 'absolute' as const,
    bottom: 10,
    left: 10,
    backgroundColor: 'rgba(6, 95, 70, 0.85)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  scannedBadgeText: {
    fontFamily: FONTS.roundedBold,
    fontSize: 9.5,
    color: '#A7F3D0',
  },
});
