import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';
import { FONTS } from '../../constants/typography';

export const mealLogStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background, // Clean Pearl Sage #F7FAF8
  },
  container: {
    padding: 16,
    paddingTop: 8,
    paddingBottom: 48,
  },
  header: {
    marginBottom: 12,
  },
  title: {
    fontFamily: FONTS.extraBold,
    fontSize: 22,
    color: '#0F2418',
    letterSpacing: -0.5,
    lineHeight: 27,
  },
  subtitle: {
    fontFamily: FONTS.medium,
    fontSize: 12.5,
    color: '#4A6354',
    marginTop: 2,
    letterSpacing: -0.1,
  },
  photoCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#2D6A4F',
    backgroundColor: '#E8F3EC',
    borderRadius: 20,
    marginBottom: 14,
  },
  photoAttached: {
    backgroundColor: '#F0FDF4',
    borderColor: '#1B432C',
  },
  photoText: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: '#1B432C',
  },
  photoSub: {
    fontFamily: FONTS.medium,
    fontSize: 11.5,
    color: '#4A6354',
    marginTop: 3,
  },
  catScroll: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  catChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    marginRight: 8,
  },
  catChipActive: {
    backgroundColor: '#1B432C',
    borderColor: '#1B432C',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  catText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: '#4A6354',
  },
  catTextActive: {
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    marginBottom: 14,
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    fontFamily: FONTS.extraBold,
    fontSize: 11,
    color: '#849C8D',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  fieldLabel: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: '#0F2418',
    marginBottom: 4,
  },
  textInput: {
    fontFamily: FONTS.medium,
    backgroundColor: '#F7FAF8',
    borderWidth: 1,
    borderColor: '#D1DDD6',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13.5,
    color: '#0F2418',
    marginBottom: 10,
  },
  
  // Dedicated Separate Sugar & Sodium Cards
  nutrientCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  nutrientCardTitle: {
    fontFamily: FONTS.bold,
    fontSize: 12.5,
    color: '#0F2418',
  },
  nutrientCardContext: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#849C8D',
  },
  nutrientInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7FAF8',
    borderWidth: 1,
    borderColor: '#D1DDD6',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginVertical: 6,
  },
  nutrientInput: {
    flex: 1,
    fontFamily: FONTS.displayExtraBold,
    fontSize: 17,
    color: '#0F2418',
    paddingVertical: 6,
  },
  nutrientUnit: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: '#4A6354',
    marginLeft: 6,
  },
  highSodiumInputWrap: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  nutrientHelperText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: '#4A6354',
    marginTop: 2,
    lineHeight: 15,
  },

  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  gridCol: {
    flex: 1,
  },
  warningBox: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#FCD34D',
    padding: 10,
    borderRadius: 14,
    marginVertical: 8,
  },
  warningText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: '#92400E',
    lineHeight: 16,
  },
  submitBtn: {
    backgroundColor: '#1B432C',
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  submitBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 14.5,
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
});
