import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../constants/colors';
import { FONTS } from '../../constants/typography';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background, // Clean Pearl Sage #F7FAF8
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 110,
  },

  // Hero / Profile Section (Framed Card Container with Modern Rounded Aesthetics)
  profileHeroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.08)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2.5,
    marginBottom: 16,
  },
  profileHorizontalRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    position: 'relative',
  },
  avatarRing: {
    padding: 3.5,
    borderRadius: 54,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: 'rgba(27, 67, 44, 0.12)',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 25,
    height: 25,
    borderRadius: 13,
    backgroundColor: '#1B432C', // SQUI Deep Logo Forest Green
    borderWidth: 2,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  profileInfoCol: {
    flex: 1,
    marginLeft: 14,
    justifyContent: 'center',
  },
  userName: {
    fontFamily: FONTS.extraBold,
    fontSize: 18,
    color: '#0F2418',
    letterSpacing: -0.4,
    lineHeight: 23,
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
    marginBottom: 6,
  },
  userEmail: {
    fontFamily: FONTS.medium,
    fontSize: 12.5,
    color: '#4A6354',
    letterSpacing: -0.1,
  },
  pillRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  journeyPill: {
    backgroundColor: '#E8F3EC',
    paddingHorizontal: 8.5,
    paddingVertical: 3,
    borderRadius: 8,
  },
  journeyPillText: {
    fontFamily: FONTS.bold,
    fontSize: 10.5,
    color: '#1B432C',
    letterSpacing: 0.1,
  },
  goalPill: {
    backgroundColor: '#FAF3EB',
    paddingHorizontal: 8.5,
    paddingVertical: 3,
    borderRadius: 8,
  },
  goalPillText: {
    fontFamily: FONTS.bold,
    fontSize: 10.5,
    color: '#D4A373',
    letterSpacing: 0.1,
  },
  editProfileIconButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#F0F5F2',
    borderWidth: 1,
    borderColor: '#E8F3EC',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginLeft: 8,
  },

  // Grouped Frame Sections
  sectionWrapper: {
    marginBottom: 18,
  },
  sectionTitle: {
    fontFamily: FONTS.extraBold,
    fontSize: 11,
    color: '#849C8D',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginLeft: 6,
  },
  frameCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 44, 0.07)',
    overflow: 'hidden',
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1.5,
  },
  menuItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  menuItemDivider: {
    height: 1,
    backgroundColor: '#F0F5F2',
    marginLeft: 54,
  },
  iconSquircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#E8F3EC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconSquircleWarm: {
    backgroundColor: '#FAF3EB',
  },
  menuItemContent: {
    flex: 1,
    justifyContent: 'center',
  },
  menuItemTitle: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#0F2418',
    letterSpacing: -0.2,
    lineHeight: 19,
  },
  menuItemSub: {
    fontFamily: FONTS.medium,
    fontSize: 11.5,
    color: '#4A6354',
    marginTop: 1.5,
    letterSpacing: -0.1,
    lineHeight: 15,
  },
  rightMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  badgePill: {
    backgroundColor: '#F0F5F2',
    paddingHorizontal: 7.5,
    paddingVertical: 3,
    borderRadius: 7,
  },
  badgePillText: {
    fontFamily: FONTS.bold,
    fontSize: 10.5,
    color: '#4A6354',
    letterSpacing: 0.1,
  },

  // SQUI Philosophy Banner
  philosophyBanner: {
    backgroundColor: '#FAF3EB',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(212, 163, 115, 0.3)',
    marginBottom: 20,
  },
  philosophyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  philosophyTag: {
    fontFamily: FONTS.extraBold,
    fontSize: 11,
    color: '#9A6B38',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  philosophyQuote: {
    fontFamily: FONTS.medium,
    fontSize: 12.5,
    fontStyle: 'italic',
    color: '#5C3F20',
    lineHeight: 18,
    letterSpacing: -0.1,
  },

  // Bottom Logout Button (High Contrast Brand Forest)
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1B432C',
    paddingVertical: 14,
    borderRadius: 18,
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 16,
    gap: 8,
  },
  logoutButtonText: {
    fontFamily: FONTS.bold,
    fontSize: 14.5,
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  versionText: {
    fontFamily: FONTS.semiBold,
    textAlign: 'center',
    fontSize: 11,
    color: '#849C8D',
    marginBottom: 8,
    letterSpacing: 0.1,
  },

  // Modal / Bottom Sheet Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 36, 24, 0.45)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    paddingBottom: Platform.OS === 'ios' ? 36 : 24,
    paddingHorizontal: 20,
    paddingTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 10,
  },
  modalDragHandle: {
    width: 38,
    height: 4,
    backgroundColor: '#D1DDD6',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: FONTS.displayBold,
    fontSize: 18,
    color: '#0F2418',
    letterSpacing: -0.4,
  },
  modalCloseText: {
    fontFamily: FONTS.bold,
    fontSize: 12.5,
    color: '#1B432C',
    backgroundColor: '#E8F3EC',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  modalBody: {
    paddingBottom: 20,
  },
  fieldLabel: {
    fontFamily: FONTS.bold,
    fontSize: 12.5,
    color: '#1B432C',
    marginBottom: 6,
    marginTop: 8,
    letterSpacing: -0.1,
  },
  fieldInput: {
    fontFamily: FONTS.medium,
    backgroundColor: '#F7FAF8',
    borderWidth: 1,
    borderColor: '#D1DDD6',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: '#0F2418',
    marginBottom: 8,
  },
  fieldInputDisabled: {
    backgroundColor: '#EEF2F0',
    borderColor: '#E2E8E5',
    color: '#849C8D',
  },
  fieldNote: {
    fontFamily: FONTS.regular,
    fontSize: 11.5,
    color: '#849C8D',
    marginBottom: 12,
    lineHeight: 16,
  },
  modalActionBtn: {
    backgroundColor: '#1B432C',
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 12,
    shadowColor: '#1B432C',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },
  modalActionBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  // FAQ Accordion Card
  faqCard: {
    backgroundColor: '#F7FAF8',
    borderWidth: 1,
    borderColor: '#E8F3EC',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
  },
  faqQuestion: {
    fontFamily: FONTS.bold,
    fontSize: 13.5,
    color: '#0F2418',
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  faqAnswer: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: '#4A6354',
    lineHeight: 18,
  },
});
