export const NUTRITION_TARGETS = {
  DEFAULT_DAILY_SUGAR_RECOMMENDED_G: 25,
  DEFAULT_DAILY_SUGAR_CAP_G: 50,
  DEFAULT_DAILY_SODIUM_CAP_MG: 2000,
  MEAL_HIGH_SODIUM_WARNING_MG: 800,
  DEFAULT_DAILY_WATER_ML: 2500,
  DEFAULT_DAILY_CALORIES_KCAL: 2000,
} as const;

export const HEALTH_THRESHOLDS = {
  SUGAR_SAFE_RATIO: 0.7, // < 70% of max is SAFE
  SUGAR_CAUTION_RATIO: 1.0, // 70-100% is CAUTION, > 100% is EXCEEDED
  SODIUM_SAFE_RATIO: 0.7,
  SODIUM_CAUTION_RATIO: 1.0,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;
